

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: prueba-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://juan98:I4mD3v3l0p3r**@cluster0.2avrkut.mongodb.net/prueba-backend?retryWrites=true&w=majority
      - JWT_SECRET=mi-super-secreto-jwt-key-para-prueba-tecnica-2024
      - JWT_EXPIRES_IN=24h
      - BCRYPT_ROUNDS=12
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio para desarrollo (opcional)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: prueba-backend-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb+srv://juan98:I4mD3v3l0p3r**@cluster0.2avrkut.mongodb.net/prueba-backend?retryWrites=true&w=majority
      - JWT_SECRET=mi-super-secreto-jwt-key-para-prueba-tecnica-2024
      - JWT_EXPIRES_IN=24h
      - BCRYPT_ROUNDS=12
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev
    profiles:
      - dev
